var compositions = {
	Kanakangi:['Sri Gananatham Bhajamyaham - Thyagaraja', 'kanakAmbari kAruNyAmRtalahari - Muthuswami Dikishitar', 'Sreesa Putraya - Dr. M. Balamuralikrishna'],
	Ratnangi:['Kalasavardhijam - Thyagaraja', 'Tarunam Ide - Koteeswara Iyer', 'Sree Gurum Chintayaamyaham - Dr. M. Balamuralikrishna' ],
	Ganamurti:['Gānamoorthe Sri Krishna - Thyagaraja', 'Pāhi Jagadİswarā - Dr. M. Balamuralikrishna', 'Brihadiswara Rakshatuma - Muthuswami Dikshitar'],
	Vanaspati:['Pariyachakama - Thyagaraja', 'ĒswarĪ JagadĪswari - Dr. M. Balamuralikrishna', 'Brihadamba madamba, Matsyavatara and Guruguha swamini - Muthuswamy Dikshitar'],
	Manavati:['Evarito ne delpudu - Thyagaraja', 'Nijabaktim - Koteeswara Iyer', 'Sri Hanumantham - Balamuralikrishna'],
	Tanarupi:['Va velava va - Koteeswara Iyer', 'Sri Rama sada bajeham - Dr. M. Balamuralikrishna', 'Chidambara natarajamurthim - Muthuswami Dikshitar'],
	Senavati:['Jalamela Raghupathe - Dr. M. Balamuralikrishna', 'Gnanambike palayamam - Muthuswami Dikshitar'],
	Hanumatodi:['Thāye Yashoda - Oottukkadu Venkata Kavi', 'Erā Nāpai - Patnam Subramania Iyer', 'Shri Krishnam Bhajamaanasa,Daakshayani and Kamalambike - Muthuswami Dikshitar'],
	Dhenuka:['TeliyalEru rAmA - Tyagaraja', 'Raavayya Rama - Dr. M. Balamuralikrishna'],
	Natakapriya:['Maara jananeem Aashraye - Nallan Chakravartula Krishnamacharyulu', 'Endukinta Kopamu - Tiruvottriyur Tyagayyar', 'Paripalaya Maam - Dr. M. Balamuralikrishna'],
	Kokilapriya:['Dasarathe Dayasaradhe - Thyagaraja', 'Vadamela Radha Manohara - Dr. M. Balamuralikrishna', 'Neeke abhimanamu - Mysore Vasudevachar'],
	Rupavati:['Ne more bettina - Thyagaraja', 'Sri Krishna bhajare - Muthuswami Dikshitar', 'Paalayamaam Sree Parvatha Nandini - Dr. M. Balamuralikrishna'],
	Gayakapriya:['Nada nilai - Koteeswara Iyer', 'Sri Mahavishnum - Dr. M. Balamuralikrishna', 'Ramachandra bhakthum - Muthuswami Dikshitar'],
	Vakulabharanam:['Gowrinatham - Oottukkadu Venkata Kavi', 'Ye ramuni nammitino - Thyagaraja', 'Nambinen ayya - Koteeswara Iyer'],
	MayamalavaGowla:['Tulasī Daḻamulacē Saṃtōṣamuga - Tyagaraja', 'Meru samāna vīra - Tyagaraja', 'Śrināthādi Guruguho - Muthuswami Dikshitar'],
	Chakravakam:['Etula Brotuvo teliya and Sugunamule - Thyagaraja', 'Kānakkankoti vendum - Koteeswara Iyer', 'Gajānanayutham - Muthuswami Dikshitar'],
	Suryakantam:['Muddumomu elagu - Thyagaraja', 'Sri Sambasivaiyya - Muthiah Bhagavatar', 'Kanavo ninaivo - Koteeswara Iyer'],
	Hatakambari:['Naraharim - Muthuswami Dikshitar', 'Alalagada - Koteeswara Iyer', 'RakshĀsumam srÎ lakshmÎ Pathe - Dr. M. Balamuralikrishna'],
	Jhankaradhwani:['Phanipati sayee - Thyagaraja', 'Varnam tharum - Koteeswara Iyer', 'hasha Kethana Pitaram - Dr. M. Balamuralikrishna'],
	Natabhairavi:['Sri Valli Devasena pathe - Papanasam Sivan', 'Parulaseva - Poochi Srinivasa Iyengar', 'Upacaharamu jeseva - Thyagaraja'],
	Kiravani:['Kaligiyunte - Thyagaraja', 'Ambavani nannu - Muthiah Bhagavatar', 'Balasarasa Murali - Oottukkadu Venkata Kavi'],
	Karaharapriya:['Chakkani Rājamārgamu, Pakkala Nilabaḍi, Mitri Bhāgyame, Rāmā nī samānamevaru, Naḍaci Naḍaci,Peridi ninnu, Chetulāra shrungāramu, Kori sevimpa rāre, Pāhi rāma rāma anuchu, Vidamu sevayave, and Rāma nīyada - Tyagaraja', 'Moovasai konda thirumal - Muthiah Bhagavatar', 'Satatam thaavaka pada sevanam - Swathi Thirunal'],
	GowriManohari:['Guruleka etuvanti - Thyagaraja', 'Varalakshmi Namostute - Mysore Vasudevacharya', 'Sarasa sama mridu pada - Swati Tirunal'],
	Varunapriya:['Yemani pogadudu - Thyagaraja', 'Samashrayami Sada - Dr. M. Balamuralikrishna', 'Singara kumari - Koteeswara Iyer'],
	Mararanjani:['Manasa srirama - Thyagaraja', 'Sharavati - Muthuswami Dikshitar', 'Ramapathina - Dr. M. Balamuralikrishna'],
	Charukesi:['Adamodi Galade - Thyagaraja', 'Karunai Varuumo - Papanasam Sivan', 'Kripaya pālaya sowrae - Swati Tirunal'],
	Sarasangi:['Jaya jaya padmanabha - Swati Tirunal', 'Sourasenesham vallisenam - Muthuswami Dikshitar', 'Nikela dayaradu - Ramaswami Sivan'],
	Harikambhoji:['Ramanannu brovara, Entara neethana and Dinamani vamsa - Thyagaraja', 'Enadu manam kavalai - Papanasam Sivan'],
	DhiraShankarabharanam:['Eduṭa Nilacitē, Bhakti Bhikṣamīyave, Maryāda Kādurā, Svararāgasudhārasa, Sundarēśvaruṇi, Manasu Svādhīnamaina and Eṃduku Peddalavalē - Tyagaraja', 'Sarōjadala Nētri and Dēvī Mīnānētri - Syama Sastri', 'Pogadirēlo Ranga - Purandara Dasa'],
	Naganandini:['Nagabharanam - Muthuswami Dikshitar', 'Sattaleni dinamu - Thyagaraja', 'Dakshayani rakshamam - Dr. M. Balamuralikrishna'],
	Yagapriya:['Kalavati kamalasyanu - Muthuswami Dikshitar', 'Sambho sadasiva - Koteeswara Iyer'],
	Ragavardhini:['Kalangadhe Maname - Koteeswara Iyer'],
	Gangayabushani:['Varadaraja avava - Muthuswami Dikshitar', 'Ninaikanome - Koteeswara Iyer', 'Evvare ramayya - Thyagaraja'],
	Vagadishwari:['Paramatmudu - Thyagaraja', 'Bhogachhaaye Naatakapriye - Muthuswami Dikshitar', 'Vani Vagadheeshwari'],
	Shulini:['Prana natha - Thyagaraja', 'Paramukhamadeno - Koteeswara Iyer', 'Nalinanarayani - Dr. M. Balamuralikrishna'],
	Calanattai:['Rājadhirāja - Baluswami Dikshitar', 'Nagātmajā Manōharam - Dr. M. Balamuralikrishna', 'Margazhi Thingal - Andal'],
	Salagam:['Ganamrudham - Koteeswara Iyer', 'VĀraÑa vadanam - Dr. M. Balamuralikrishna'],
	Jalavarnam:['Kanaka mayura - Koteeswara Iyer', 'Maheswari kavuma uma - Dr. M. Balamuralikrishna'],
	Jhalavarali:['Narami sri rama - Thyagaraja', 'Madhava dayya - Dr. M. Balamuralikrishna', 'Anada rakshaka - Thyagaraja'],
	Navneetam:['Umāpati pāhi by Dr. M. Balamuralikrishna', 'Lēmidelpa peddavāru - Thyagaraja', 'Sami ide nalla samayam - Koteeswara Iyer'],
	Pavani:['Sachidanandamaya - Muthuswami Dikshitar', 'Anjaade - Koteeswara Iyer'],
	Raghupriya:['Khalitaka vamsa - Dr. M. Balamuralikrishna', 'Himagiri kumari - Muthuswami Dikshitar', 'Sadananda - Koteeswara Iyer'],
	Ghavambhodi:['Veera raghava - Koteeswara Iyer', 'Vinati chakonavayya - Dr. M. Balamuralikrishna', 'Namomasti geervani - Muthuswami Dikshitar'],
	Bhavapriya:['Srikanta niyeda - Thyagaraja', 'Sentiru velan - Koteeswara Iyer', 'Vennai tirudi - Periyasaamy Thooran'],
	Shubhapantuvarali:['Ennalu orake - Thyagaraja', 'Sri Satyanarayanam - Muthuswami Dikshitar', 'Pahimaam payoraasi - Kalyani Varadarajan'],
	Shadvidamargini:['Jnanam Osaga Rada - Thyagaraja', 'Andaranga Bhakthi - Koteeswara Iyer', 'HaimavathÊ bHaja mĀnasa - Dr. M. Balamuralikrishna'],
	Suvarnangi:['Sri raghupathim - Dr. M. Balamuralikrishna', 'Sarasa souveera - Muthuswami Dikshitar', 'Iha para sukha - Koteeswara Iyer'],
	Divyamani:['Leela ganu joochi - Thyagaraja', 'Appa muruga - Koteeswara Iyer'],
	Dhavalambari:['Karvaya kanda - Koteeswara Iyer', 'Srivani pustaka pani - Dr. M. Balamuralikrishna', 'Sringaradi - Muthuswami Dikshitar'],
	Namanarayani:['En maname - Koteeswara Iyer', 'Narmada kaveri - Muthuswami Dikshitar', 'Mahadeva pahimam - Dr. M. Balamuralikrishna'],
	Kamavardhini:['Shambo mahadeva - Thyagaraja', 'Enna ganu rama - Bhadrachala Ramadas', 'Ninnarul Iyambalagumo - Papanasam Sivan'],
	Ramapriya:['Saamodam Paripaalaya - Swathi Thirunal Rama Varma', 'Mahadevamanisham - Mangalampalli Balamuralikrishna', 'Korinavara mosagu - Patnam Subramania Iyer'],
	Gamanashrama:['Sri chakrapura vasini - Muthiah Bhagavatar', 'Idu neeku nyayama - Mysore Vasudevachar', 'Ubhaya kaveri - Veene Sheshanna'],
	Vishwambari:['Vamshavati shiva yuvati and Bhaktavatsalam - Muthuswami Dikshitar','Paramananda - Koteeswara Iyer'],
	Shamalangi:['Veera raghava - Koteeswara Iyer','Vinati chakonavayya - Dr. M. Balamuralikrishna', 'Namo namaste geervani - Muthuswami Dikshitar'],
	Shanmughapriya:['Vaddane vaaru - Tyagaraja','Marivere Dikkevarayya - Patnam Subramania Iyer', 'Valli Nayakane - Muthiah Bhagavatar'],
	SimhendraMadhyamam:['Needu charanamule - Thyagaraja','Ashaindhadum mayil onDru - Oottukkadu Venkata Kavi','Ayyappa - Yesudas'],
	Hemavati:['Sree Kanthimathim - Muthuswami Dikshitar', 'Ika talanenura ina - S. Ramanathan', 'Neesarisaati - Tyagaraja'],
	Dharmavati:['Parandaamavati Jayathi - Muthuswami Dikshitar','Ododi vandhen kanna - Ambujam Krishna'],
	Nitimati:['Vachamgochara - Thyagaraja','Mohanakara muthu - Koteeswara Iyer','Smaranam - Dr. M. Balamuralikrishna'],
	Kantamani:['Nadasukam - Koteeswara Iyer', 'Bhuvaneshwari pahi - Dr. M. Balamuralikrishna', 'Palintuvo - Thyagaraja'],
	Rishabhapriya:['Ghana naya desika - Koteeswara Iyer', 'Maara ratipriyam - Muthuswami Dikshitar', 'Nandisam vande - Dr. M. Balamuralikrishna'],
	Latangi:['Diname sudhinamu - Thyagaraja', 'Aparadhamula - Thyagaraja', 'Marivere and Aparadamulan - Patnam Subramania Iyer'],
	Vachaspati:['Pahi Jaga janani - Swathi thirunal', 'Kantajoodumi - Thyagaraja', 'Paraatparaa - Papanasam Sivan'],
	Mechakalyani:['Vanajāksha and Needu Charana - Pallavi Gopala Iyer', 'Nidhi chāla sukhamā, Etavunnārā, Sundari nī Divya, Ammā Rāvammā and Vāsudēvanyani - Tyagaraja', 'Kamalāmbāṃ bhajarē ,Bhajarē Recita, ShivaKameshwari Chintayeham - Muthuswami Dikshitar'],
	Chitrambari:['Sri rama nelami - Dr. M. Balamuralikrishna', 'Samaganalola - Koteeswara Iyer'],
	Sucaritra:['Chintayami santatam - Dr. M. Balamuralikrishna', 'Velu mayil - Koteeswara Iyer', 'Santana manjari - Muthuswami Dikshitar'],
	Jyotiswarupini:['Anandamayamanave - Walajapet Venkataramana Bhagavathar', 'Gaanamrutha paanam - Koteeswara Iyer', 'Jyotiswaroopini - Periyasaamy Thooran'],
	Dhatuvardani:['Sukha kara - Koteeswara Iyer', 'Mahesham bhavayam - Dr. M. Balamuralikrishna'],
	Nasikabhushani:['Maravairi ramani - Thyagaraja', 'Thandarul ayya - Koteeswara Iyer', 'Srirama Saraswathi - Muthuswami Dikshitar'],
	Kosalam:['Sri chakrapura vasini - Muthiah Bhagavatar', 'Idu neeku nyayama - Mysore Vasudevachar', 'Ubhaya kaveri - Veene Sheshanna'],
	Rasikapriya:['Arul seyya - Koteeswara Iyer', 'Pavana tanaya pĀlayamĀm - Dr. M. Balamuralikrishna', 'Sringara rasamanjarim - Muthuswami Dikshitar']

}